name: Production

on:
  pull_request:
    branches:
      - production

jobs:
  tag:
    if: ${{ github.head_ref == "staging" }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: 'Definir tag caso a branch head seja staging'
        run: |
          prev_tag=$(git describe --tags --abbrev=0)
          readarray -d "." -t array <<< "$prev_tag"
          TAG_NAME=${array[0]}"."$((array[1] + 1))
          git tag $TAG_NAME
          git push origin $TAG_NAME