name: Stabilization

on:
  pull_request:
    branches:
      - staging

jobs:
  tag:
    if: ${{ github.head_ref  == "main" }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Definir tag caso a brach head seja main'
        run: |
          prev_tag=${git describe --tags --abbrev=0}
          readarray -d "." -t array <<< "$prev_tag"
          TAG_NAME=${array[0]}"."$((array[1] + 1))
          git tag $TAG_NAME
          git push origin $TAG_NAME